version: '3.8'
services: 
  app:
    build: .
    ports:
      - "8000:8000"
    image: django_image
    container_name: django_container
    command: python Solstice/manage.py runserver 0.0.0.0:8000
