services: 
  app:
    build: .
    ports:
      - "8000:8000"
    image: django_image
    container_name: django_container
    command: python Solstice/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - solstice_network

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - solstice_network

networks:
  solstice_network:
