### Signup Request
POST http://localhost:8000/signup/
Content-Type: application/json

{
    "username": "newuser1",
    "password": "newpassword",
    "first_name": "New",
    "last_name": "User1",
    "email": "newuser1@example.com"
}

### Login Request
POST http://localhost:8000/login/
Content-Type: application/json

{
    "username": "newuser1",
    "password": "newpassword"
}