### Test Signup Endpoint
POST http://localhost:8000/signup/
Content-Type: application/json

{
  "username": "testuser2",
  "first_name": "Test",
  "last_name": "User",
  "email": "testuser1@example.com",
  "password": "testpassword"
}

### Test Login - POST Request with Valid Credentials
POST http://localhost:8000/login/
Content-Type: application/json

{
  "username": "testuser2",
  "password": "testpassword"
}

###

### Test Login - POST Request with Invalid Credentials
POST http://localhost:8000/login/
Content-Type: application/json

{
  "username": "invalid_username",
  "password": "invalid_password"
}